### ISSUE TITLE
The `esbonio.sphinx.confDir` keeps changing to windows-like path

### ISSUE THREAD

**Issue by nandgator** [swyddfa/esbonio#376] opened 2022-04-26 04:14 UTC
Hi, I've observed that in vscode's `settings.json`, this

```json
{
    "esbonio.sphinx.confDir": "${workspaceFolder}/docs/source"
}
```

is replaced with:

```json
{
    "esbonio.sphinx.confDir": "${workspaceFolder}\\docs\\source"
}
```

For mainly two reasons:
 - keep it consistent with other path formats
 - does not cause an issue when the config is used in a cross-platform setup
 
Is it possible to curb this behavior?

---

> Probably related #322

**Comment by alcarney** [comment] 2022-04-26 19:05
This is due to how the vscode-restructuredtext extension handles the configuration values, so there is not much that can be done from this repo.

I have commented on vscode-restructuredtext/vscode-restructuredtext#362 with what I think is the cause.

I will close this issue and we can continue investigating over on the other repo

**Closed as completed by alcarney** 2022-04-26 19:05 UTC
Labels: vscode-restructuredtext
