### ISSUE TITLE
Esbonio server start command should quote the python path

### ISSUE THREAD

**Issue by DiegoF90** [swyddfa/esbonio#541] opened 2023-02-15 13:54 UTC
Starting the server when using a default python path with spaces fails.
For example:

`Server start command: C:\Program Files (x86)\python\env_local\Scripts\python.exe -m esbonio`

Fails with:

`'C:\Program' is not recognized as an internal or external command, operable program or batch file.`

**Comment by alcarney** [comment] 2023-02-15 18:51
Unfortunately, I’m struggling to reproduce this on my Windows install…

Can I confirm that you are using the [Esbonio VSCode extension](https://marketplace.visualstudio.com/items?itemName=swyddfa.esbonio) and if so what version?
I ask since the [reStructuredText](https://marketplace.visualstudio.com/items?itemName=lextudio.restructuredtext) extension also has support for esbonio and judging by the comments in https://github.com/vscode-restructuredtext/vscode-restructuredtext/issues/406 it may or may not still be affected by this issue.

**Comment by alcarney** [comment] 2023-10-11 22:23
Closing as this is most likely a duplicate of #658 and not something that can be fixed from this repo.
Feel free to reopen if this is in fact an issue with the [Esbonio](https://marketplace.visualstudio.com/items?itemName=swyddfa.esbonio) extension!

**Closed as completed by alcarney** 2023-10-11 22:23 UTC
Labels: vscode-restructuredtext
