### ISSUE TITLE
How to start the language server?

### ISSUE THREAD

**Issue by skycaptain** [swyddfa/esbonio#346] opened 2022-04-03 21:13 UTC
Since the reStructuredText extension now requires esbonio for previewing, I though I would give it a try. However, I encountered multiple issues, with even setting this thing up.

I have a project with a virtual environment under `${workspaceFolder}/.venv`. There, I install esbonio as recommended using `pip install esbonio`. Then, I installed the reStructuredText extension, which also installs the esbonio extension.

Issue 1: After installation, I immediately got the Error from VSCode "Unable to start language server. See output window for more details". Unfortunately, the output window is no help as I can only see this:

```plain
[Log - 10:54:13 PM] ConfigurationChangeEvent
[Log - 10:54:13 PM] ==================== RESTARTING SERVER =====================
```

Issue 2: After, issue 1 I checked my setting, which are all default btw. I saw that the default entry point is `esbonio`. I took that as a hint that the VSCode extension would just call `esbonio` in my venv. So, I tried to run that command manually, which gives me:

```plain
$ esbonio
Traceback (most recent call last):
  File "[redacted]/.venv/bin/esbonio", line 8, in <module>
    sys.exit(main())
TypeError: main() missing 1 required positional argument: 'cli'
```

Which is no surprise, since this line references the main function directly, which expects one argument (instead of referencing `__main__` or a wrapper): https://github.com/swyddfa/esbonio/blob/d3eaf0449e68117cd1d176cb43c5b07f742cce84/lib/esbonio/setup.cfg#L44 

Issue 3: I concluded that the main entry point is misconfigured, so I set the VSCode setting to `python3 -m esbonio`, which at least started the language server on the command line. But still no luck from VSCode.

How do I install and setup this extension properly? The instructions from the documentation and the out-of-box configuration do not seem to work.

**Comment by lextm** [comment] 2022-04-03 21:48
For such issues, please report to vscode-restructuredtext with all details required by the wizard,

https://github.com/vscode-restructuredtext/vscode-restructuredtext/issues/new/choose

**Comment by skycaptain** [comment] 2022-04-03 22:22
Hmm. Weird. The esbonio extension shipped with the reStructuredText extension does not seem to work, but the standalone esbonio extension at least brings me to the next issue (https://github.com/swyddfa/esbonio/issues/341 on MacOS).

The misconfigured entry point is still a code smell IMHO.

**Comment by alcarney** [comment] 2022-04-04 18:36
I'm less familiar with the internals of the vscode-restructuredtext extension, but you should be able to get more information in the output window if you set `esbonio.server.logLevel = "debug"`

Good spot on the entry point, I'll get on to fixing that.

**Comment by skycaptain** [comment] 2022-04-04 18:54
> I'm less familiar with the internals of the vscode-restructuredtext extension, but you should be able to get more information in the output window if you set esbonio.server.logLevel = "debug"

I did that, but it didn't give me any more details. I suspect the setting you mentioned is for the server itself, but the problem is that the server won't even start. As @lextm suggested this seems to be an issue of the vscode-restructuredtext extension and should be further investigated in their project.

**Comment by rainerth** [comment] 2022-04-09 16:31
Same behavior on my site. I have a Linux and an Windows system with similar settings. On my Linux system with the same settings vscode starts esbonio correct.

On Windows vscode displays "esbonio: Failed" / "Unable to start language server. See output window for more details". There no further details in the output window except "RESTARTING SERVER".

Starting esbonio within an vscode terminal (Windows) there are no issures.   

C:\Users\...>python -m esbonio --version
v0.10.3

C:\Users\...>esbonio --version
v0.10.3

**Comment by alcarney** [comment] 2022-04-26 19:09
@skycaptain @rainerth there's been a few releases of both the language server and the vscode-restructuredtext extension since this was opened - is this still an issue for you? Or can this be closed?

**Comment by skycaptain** [comment] 2022-04-27 07:46
@alcarney Thanks for the help so far. I updated all vscode extensions as well as the esbonio Python package in my venv to their latest version and dropped the vscode-restructuredtext extension for now. I seems that the esbonio server is starting now and I can see that the Sphinx documentation is generated. However, I still can not preview a document inside VSCode. In the Esbonio Output window I get the following error: `Cancel notification for unknown message id "2"`. In the Developer Console I get this error message:

```
  ERR Header must provide a Content-Length property.: Error: Header must provide a Content-Length property.
    at m.onData ([redacted]/.vscode/extensions/swyddfa.esbonio-0.8.3/dist/extension.js:1:70416)
    at Socket.<anonymous> ([redacted]/.vscode/extensions/swyddfa.esbonio-0.8.3/dist/extension.js:1:70137)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
```

Let me know, if I should open a separate ticket for this issue.

**Comment by alcarney** [comment] 2022-04-27 22:03
Hmm... it's not obvious to me what could be wrong... 
Are you able to set `esbonio.server.logLevel = "debug"` and share the contents of the output window? 

The preview works by spinning up a `http.server` in the build directory and showing it in a webview in VSCode. So I'm hoping to see some messages like the following 
```
[esbonio.lsp] esbonio.server.preview: {'show': False}
[esbonio.lsp] Starting preview server.
[client] Result is {"port":43435}
[client] Previewing /index.html
```

Hopefully whatever we do (or don't) see will help shed some light on the issue...

> ```
>   ERR Header must provide a Content-Length property.: Error: Header must provide a Content-Length property.
>    at m.onData ([redacted]/.vscode/extensions/swyddfa.esbonio-0.8.3/dist/extension.js:1:70416)
>    at Socket.<anonymous> ([redacted]/.vscode/extensions/swyddfa.esbonio-0.8.3/dist/extension.js:1:70137)
>    at Socket.emit (node:events:390:28)
>    at addChunk (node:internal/streams/readable:315:12)
>    at readableAddChunk (node:internal/streams/readable:289:9)
>    at Socket.Readable.push (node:internal/streams/readable:228:10)
>    at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
> ```

This makes it sound like the server is printing log messages or something else outside of the LSP spec.... will have to have a think on how we could capture this.... :thinking:

**Comment by alcarney** [comment] 2022-04-27 23:19
So good news and not so good news.

Good news is I can reproduce the `ERR Header must provide a Content-Length property.:` message by inserting a random print statement into the language server which also seems to have the effect of completely breaking the server from there on out, forcing me to restart VSCode.

Kind of good news, I'm able to have VSCode print out all output from the server to the console, including my random print statement
![image](https://user-images.githubusercontent.com/2675694/165645619-736173b4-862b-4cac-a8e5-f0340cd78482.png)

Not so good news, the only way I've found so far to make this happen is to edit the `.vscode/extensions/swyddfa.esbonio-0.8.3/dist/extension.js` file (which is minimized)

```
onData(e) { console.log(Buffer.from(e.buffer).toString()); for (this.buffer.append(e); ;) { if (-1 === this.nextMessageLength) { const e = this.buffer.tryReadHeaders(); if (!e) return; const t = e.get("Content-Length"); if (!t) throw new Error("Header must provide a Content-Length property.");
            ^ I added this console.log statement
```
**Note** I'm really not expecting you to replicate this (unless you're feeling super motivated) this is mainly for future me to reference :) 

I think however, I might be able to do something on the Python side... :thinking:

**Comment by alcarney** [comment] 2022-05-09 22:04
@skycaptain v0.11.2 of the language server is now out and it comes with the ability to record all of its input and output to a text file.

You'll have to install the [`lsp-devtools`](https://pypi.org/project/lsp-devtools/) package before hand, but could you try running the server again with the `esbonio.server.startupModule` option set to `esbonio.lsp.sphinx._record`?

This should create a file `lsp.log` in the root of your workspace containing all output sent to and from the server e.g.
```
Content-Length: 64
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"jsonrpc": "2.0", "method": "esbonio/buildStart", "params": {}}
Content-Length: 145
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"jsonrpc": "2.0", "method": "window/logMessage", "params": {"type": 4, "message": "building [mo]: targets for 0 po files that are out of date"}}
Content-Length: 152
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"jsonrpc": "2.0", "method": "window/logMessage", "params": {"type": 4, "message": "building [html]: targets for 13 source files that are out of date"}}
```
No need to share the whole thing, but can you look to see if there is anything in there that doesn't look like it fits the pattern above? Hopefully we'll see what's causing the `ERR Header must provide a Content-Length property.` errors in VSCode

**Comment by skycaptain** [comment] 2022-05-14 17:59
Hmm. I followed your instructions. This is the content that is added to `lsp.log` once I execute "Esbonio: Open Preview on the Side" on `index.rst` in VSCode:

```plain

{"jsonrpc":"2.0","id":5,"method":"textDocument/codeAction","params":{"textDocument":{"uri":"file:///[redacted]index.rst"},"range":{"start":{"line":0,"character":0},"end":{"line":0,"character":0}},"context":{"diagnostics":[]}}}
Content-Length: 41
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"jsonrpc": "2.0", "id": 5, "result": []}
Content-Length: 209

{"jsonrpc":"2.0","id":6,"method":"textDocument/documentLink","params":{"textDocument":{"uri":"file:///[redacted]index.rst"}}}
Content-Length: 41
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"jsonrpc": "2.0", "id": 6, "result": []}
Content-Length: 314

{"jsonrpc":"2.0","id":7,"method":"textDocument/codeAction","params":{"textDocument":{"uri":"file:///[redacted]index.rst"},"range":{"start":{"line":13,"character":16},"end":{"line":13,"character":16}},"context":{"diagnostics":[]}}}
Content-Length: 62

{"jsonrpc":"2.0","method":"$/cancelRequest","params":{"id":5}}
Content-Length: 41
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"jsonrpc": "2.0", "id": 7, "result": []}
Content-Length: 244

{"jsonrpc":"2.0","id":8,"method":"textDocument/definition","params":{"textDocument":{"uri":"file:///[redacted]index.rst"},"position":{"line":4,"character":19}}}
Content-Length: 41
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"jsonrpc": "2.0", "id": 8, "result": []}
Content-Length: 312

{"jsonrpc":"2.0","id":9,"method":"textDocument/codeAction","params":{"textDocument":{"uri":"file:///[redacted]index.rst"},"range":{"start":{"line":4,"character":19},"end":{"line":4,"character":19}},"context":{"diagnostics":[]}}}
Content-Length: 62

{"jsonrpc":"2.0","method":"$/cancelRequest","params":{"id":7}}
Content-Length: 41
Content-Type: application/vscode-jsonrpc; charset=utf-8

{"jsonrpc": "2.0", "id": 9, "result": []}
```

**Comment by alcarney** [comment] 2022-05-14 18:26
Hmm, that's not as enlightening as I'd hoped... we at least should be able to see the request from VSCode to the server to start the server used to drive the preview. If you search the file for `workspace/executeCommand` does that turn up anything?

**Comment by alcarney** [comment] 2022-05-14 18:39
Oh! And if you haven't already can you set `esbonio.server.logLevel` to `debug`

**Comment by lextm** [comment] 2022-10-13 06:45
Virtual environment solutions have been tested on vscode-restructuredtext side and I cannot reproduce this issue with esbonio,

https://docs.restructuredtext.net/articles/prerequisites#virtual-environments

I assume this issue can be closed now as nothing else is needed.

**Comment by alcarney** [comment] 2023-01-14 18:27
I'm going to close this, but feel free to open a fresh issue if you're still having issues.

**Closed as completed by alcarney** 2023-01-14 18:27 UTC
Labels: vscode-restructuredtext
