### ISSUE TITLE
RestructuredText files not recognised when extension is different from .rst

### ISSUE THREAD

**Issue by davbeek** [swyddfa/esbonio#425] opened 2022-07-02 19:02 UTC
Adding the setting:
```
    "files.associations": {
        "*.inc": "restructuredtext"
    },
```
to `settings.json` from VSCode, should make esbonio recognise `.inc` files as restructuredText, which is not the case.

Consider the file `top.rst` which includes the file `sub.inc`:

File `top.rst`:
```
Some heading
============

.. include:: sub.inc
```

File `sub.inc`:
```
Other heading
=============

    First line
Second line
```

- When file `sub.inc` is opened, it does not show up in the Esbonio Outline sub view of the Explorer view in the Side Bar, whereas it does show up in the Outline view of the RestructuredText Syntax Highlighting extension.
- The syntax error caused by the incorrect indentation of "First line" vs. "Second line" is properly shown in the PROBLEMS tab of the Panel, but it is not indicated in the `sub.inc` file. Clicking on the error in the PROBLEMS tab opens a second tab in the Editor on the `sub.inc` file with the error message: "The error could not be opened because the file was not found".

Note that I include the file as an `.inc` file, because including it as an `.rst` file causes double parsing by sphinx (once because sphinx parses all `rst` files, detecting orphan files in this way, and once as included text in `top.rst`), which can lead to errors. I use `include` directives for long files for which I want to generate a single html file, but multiple source files for ease of editing.

**Comment by alcarney** [comment] 2022-07-02 22:54
Interesting approach! I usually configure Sphinx to ignore filenames starting with an `_` - wouldn't have thought about using a different extension

Anyway... I don't think it will necessarily be difficult to support this, but it may require a bit of thought to make sure that the required info finds its way to the right places.

For now I'm just going to leave some notes here for future me to reference :) 

---
> "The editor could not be opened because the file was not found".

This is because, for some reason, the server is not providing the full uri to the file
```json
{
    "uri": "file:///docs/lsp/test.inc",  // <- missing workspace root
    "diagnostics": [
        {
            "range": {
                "start": {
                    "line": 4,
                    "character": 0
                },
                "end": {
                    "line": 5,
                    "character": 0
                }
            },
            "message": "Block quote ends without a blank line; unexpected unindent.",
            "severity": 2,
            "source": "sphinx"
        }
    ]
}
```
----
> When file sub.inc is opened, it does not show up in the Esbonio Outline sub view of the Explorer view in the Side Bar

This is due to [`read_initial_doctree`](https://github.com/swyddfa/esbonio/blob/ea8311a2b79ab8ef74157e9d5b2635e6b7b6a9e9/lib/esbonio/esbonio/lsp/rst/io.py#L197) checking to see if the docutils parser supports the file extension - is there a way to check the language id of the document instead? - ~Looks like we might need to fix openlawlibrary/pygls#212 first~ Fixed upstream, waiting for a release

**Comment by davbeek** [comment] 2022-07-03 06:49
Thanks for taking this up!

**Comment by alcarney** [comment] 2022-07-31 19:09
`v0.14.0` is now out on PyPi and should be available through conda in a few hours. I *think* it addresses all the issues you raised here, let me know if any issues persist.

**Comment by davbeek** [comment] 2022-08-01 10:16
I tried in a short time to test all functionality, and as far as I have been able to find, everything works perfectly now, with one single exception:

When activating an `.inc` file, which is included in an `.rst` file (`sub.inc` from my example above), the esbonio previewer does not change: it does not show the activated `.inc` file in the previewer. When, instead, an `.rst` file is included, and activated, it does show in the previewer, even though both the `.inc` file and `.rst` file are declared to be of the same restructured text file type.

**Comment by alcarney** [comment] 2022-08-01 22:04
Interesting I'm unable to get the previewer open at all for the included `rst` files in esbonio's docs... 

If I'm remembering right... the VSCode extension looks in the project's build folder for a HTML file that mirrors the path of the `rst` file relative to the src folder - something that won't work for included files... :thinking:

**Comment by lextm** [comment] 2022-08-02 02:56
Nothing is generated for the `.inc` file, as its contents are included in the `.rst` file instead. Thus, there is nothing to preview either.

A lot has to be changed (like how sphinx works internally) in order to preview partial files like `.inc` so I wonder how much community interest is there to spend time on that.

**Comment by davbeek** [comment] 2022-08-02 07:38
Good point. So, the normal way would be to use `.rst` extensions also for included files. This means that Sphinx generates html twice for included files: once for the stand-alone included file and once for the including file. 

If this would lead to errors, such as a duplicate label error, the extension can be changed, to `inc` for example, while declaring `inc` to be of type restructuredtext. Thus, no code would be generated for the `.inc` file, thus no errors, but also no preview. I think that is acceptable behavior.

**Comment by alcarney** [comment] 2022-08-02 23:26
I would assume though, that if a preview for an included file was requested, the correct/expected behavior would be for the preview to show the HTML file that contains the contents of the `inc` file? - rather than trying to generate a partial preview/doing nothing

**Comment by davbeek** [comment] 2022-08-03 07:20
I didn't think of that option, but that would very much improve the user experience. Doing nothing is indeed not what the user expects.

By the way, I don't know why you are unable to get a preview for included `.rst` files. I have done nothing special to obtain this behavior, but I like it very much: it is exactly what I would like to see. I use included files for long pages, and getting a preview for an included `.rst` file is much better for me than getting a preview for the including document. However, for included `.inc` files, such behavior appears to be impossible.

One of the reasons for preferring a preview of an included `.rst` file, as is the current behavior, is that after every save, the previewer reloads the view to the start of the file, so it loses the position in the file. So after every save, I need to scroll back, or click back to the position in the previewed file that was visible. Note that this behavior is different from browsers, which stick to the same displayed position when refreshing the page.

**Comment by alcarney** [comment] 2022-08-03 21:52
> I don't know why you are unable to get a preview for included .rst files

I assume it’s because any `rst` file I include starts with a `_` character and I’ve [configured Sphinx](https://github.com/swyddfa/esbonio/blob/d2dfb6f6247e83764d8d6af46aaeb0d2da9ab3ce/docs/conf.py#L78) to ignore them.

On the flip side I’d assume it would be possible to enable previews for `inc` files by configuring Sphinx to include them - but I expect that would negate why you use `inc` files in the first place 😅

**Comment by davbeek** [comment] 2022-08-04 07:23
> On the flip side I’d assume it would be possible to enable previews for inc files by configuring Sphinx to include them - but I expect that would negate why you use inc files in the first place 😅

Indeed 😅. 

Great that you have opened the #440 issue!

**Comment by alcarney** [comment] 2022-08-16 19:01
I think it's safe to close this issue now? If not feel free to re-open :)

**Closed as completed by alcarney** 2022-08-16 19:01 UTC
Labels: bug, lsp
